// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASqSNc7uMn_Fe1BxzBNS0js33UDIbflrc',
    appId: '1:622969585526:web:279f96b1f2a019cc79c457',
    messagingSenderId: '622969585526',
    projectId: 'empire-f8c4b',
    authDomain: 'empire-f8c4b.firebaseapp.com',
    storageBucket: 'empire-f8c4b.appspot.com',
    measurementId: 'G-3M2PHSPWMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVP7hQUg77LpmAicEonfjDC2nGHuO60Sg',
    appId: '1:622969585526:android:9a205ac466948a9c79c457',
    messagingSenderId: '622969585526',
    projectId: 'empire-f8c4b',
    storageBucket: 'empire-f8c4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYNw8cg5FAZAO5VFRwtKKTrQ6Dwr3-RIE',
    appId: '1:622969585526:ios:091e7dc57cfee90879c457',
    messagingSenderId: '622969585526',
    projectId: 'empire-f8c4b',
    storageBucket: 'empire-f8c4b.appspot.com',
    iosBundleId: 'com.example.empire',
  );
}
